# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://gaussie.github.io
date_format: "ordinal"
title: Tmylla
subtitle: "I took the one less traveled by, that has made all the difference."
description: "The Road Not Taken"
keywords: 季一帆, misite_J, tmylla 
# timezone: Asia/Chengdu
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: tmylla
# organization: UESTC
# organization_url: http://www.uestc.edu.cn
github_username: tmylla
location: Beijing, China
email: misite_J@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Homepage

  -
    href: /cv/
    label: CV

  -
    href: /publications/
    label: Publications

  -
    href: /categories/
    label: Blog

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: tmylla/tmylla.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# # !!!重要!!! 请修改下面这些信息为你自己申请的
# # !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#     username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: tmylla
#     repo: blog-comments
#     oauth:
#         client_id: d2e1cbbd298958076462
#         client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: tmylla
#     repo: blog-comments
#     clientID: d2e1cbbd298958076462
#     clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# # 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-169315486-1
github: [metadata]
